import type { LiveStream, LiveChatMessage, GuestCreator } from './types';

const DEMO_AVATAR_1 = 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80';
const DEMO_AVATAR_2 = 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80';
const DEMO_AVATAR_3 = 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80';
const DEMO_AVATAR_4 = 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=240&q=80';

export const demoGuestCreators: Record<string, GuestCreator[]> = {
  'stream-1': [
    { id: 'guest-1', name: 'BassKreyol', avatar: DEMO_AVATAR_3, role: 'co-host', status: 'live' },
  ],
  'stream-3': [
    { id: 'guest-2', name: 'NeonKreyol', avatar: DEMO_AVATAR_1, role: 'battle-opponent', status: 'live' },
    { id: 'guest-3', name: 'SunVox', avatar: DEMO_AVATAR_4, role: 'performer', status: 'accepted' },
  ],
};

export const demoStreams: LiveStream[] = [
  {
    id: 'stream-1',
    title: 'Kompa Futura Live Session',
    description: 'Live production session — building a new Kompa track from scratch with AI vocal layers. Drop your ideas in chat!',
    type: 'creator_livestream',
    status: 'live',
    creatorId: 'creator-1',
    creatorName: 'NeonKreyol',
    creatorAvatar: DEMO_AVATAR_1,
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    viewerCount: 1842,
    peakViewerCount: 2100,
    guestCreators: demoGuestCreators['stream-1'],
    tags: ['Kompa', 'Live Production', 'AI Music'],
    tipTotal: 148.50,
    chatEnabled: true,
    reactionsEnabled: true,
  },
  {
    id: 'stream-2',
    title: 'AIXENTRA AI Symphony — Neural Midnight',
    description: 'An AI-generated orchestral concert experience. Immersive visuals + adaptive generative music.',
    type: 'ai_concert',
    status: 'live',
    creatorId: 'creator-2',
    creatorName: 'VibeForge',
    creatorAvatar: DEMO_AVATAR_2,
    coverUrl: 'https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    viewerCount: 3204,
    peakViewerCount: 4000,
    guestCreators: [],
    tags: ['AI Concert', 'Orchestral', 'Generative'],
    tipTotal: 312.00,
    chatEnabled: true,
    reactionsEnabled: true,
  },
  {
    id: 'stream-3',
    title: '🥊 Remix Battle — Trap vs. Afrobeat',
    description: 'NeonKreyol vs. SunVox. Two producers. One beat. You vote the winner!',
    type: 'remix_battle',
    status: 'live',
    creatorId: 'creator-3',
    creatorName: 'DrumCode',
    creatorAvatar: DEMO_AVATAR_3,
    coverUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    viewerCount: 921,
    peakViewerCount: 960,
    guestCreators: demoGuestCreators['stream-3'],
    tags: ['Battle', 'Trap', 'Afrobeat'],
    tipTotal: 75.00,
    chatEnabled: true,
    reactionsEnabled: true,
  },
  {
    id: 'stream-4',
    title: 'Chill Lo-fi Listening Party 🎧',
    description: 'Cozy listening session — curated lo-fi beats, community picks, and a relaxed vibe.',
    type: 'listening_party',
    status: 'scheduled',
    creatorId: 'creator-4',
    creatorName: 'CrépusculeWave',
    creatorAvatar: DEMO_AVATAR_4,
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    viewerCount: 0,
    peakViewerCount: 0,
    guestCreators: [],
    tags: ['Lo-fi', 'Chill', 'Community'],
    tipTotal: 0,
    chatEnabled: true,
    reactionsEnabled: true,
  },
  {
    id: 'stream-5',
    title: 'Drill Production Masterclass',
    description: 'Live breakdown of drill beat construction — 808s, hi-hats, and AI melody generation.',
    type: 'creator_livestream',
    status: 'scheduled',
    creatorId: 'creator-2',
    creatorName: 'VibeForge',
    creatorAvatar: DEMO_AVATAR_2,
    coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    viewerCount: 0,
    peakViewerCount: 0,
    guestCreators: [],
    tags: ['Drill', 'Masterclass', 'Production'],
    tipTotal: 0,
    chatEnabled: true,
    reactionsEnabled: true,
  },
  {
    id: 'stream-6',
    title: 'Gospel Fusion Night',
    description: 'Live gospel meets electronic production. Spirit-filled, AI-enhanced.',
    type: 'creator_livestream',
    status: 'ended',
    creatorId: 'creator-1',
    creatorName: 'NeonKreyol',
    creatorAvatar: DEMO_AVATAR_1,
    coverUrl: 'https://images.unsplash.com/photo-1598030473568-00555e87c827?auto=format&fit=crop&w=1200&q=80',
    scheduledAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    viewerCount: 0,
    peakViewerCount: 1540,
    guestCreators: [],
    tags: ['Gospel', 'Fusion', 'Electronic'],
    tipTotal: 220.00,
    chatEnabled: false,
    reactionsEnabled: false,
  },
];

export const demoChatMessages: LiveChatMessage[] = [
  {
    id: 'msg-1',
    streamId: 'stream-1',
    userId: 'user-a',
    userName: 'MelodyHunter',
    userAvatar: DEMO_AVATAR_3,
    content: 'This beat is FIRE 🔥🔥',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    type: 'message',
  },
  {
    id: 'msg-2',
    streamId: 'stream-1',
    userId: 'user-b',
    userName: 'BassDropKing',
    userAvatar: DEMO_AVATAR_4,
    content: 'Can you add some reverb to the vocals?',
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    type: 'message',
  },
  {
    id: 'msg-3',
    streamId: 'stream-1',
    userId: 'user-c',
    userName: 'HypeMaster99',
    userAvatar: DEMO_AVATAR_2,
    content: '💜 Tipped $5.00 — keep it going!',
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    type: 'tip',
    tipAmount: 5.00,
  },
  {
    id: 'msg-4',
    streamId: 'stream-1',
    userId: 'user-d',
    userName: 'SoundWave',
    userAvatar: DEMO_AVATAR_1,
    content: 'The AI layers are sounding so smooth!',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    type: 'message',
  },
  {
    id: 'msg-5',
    streamId: 'stream-1',
    userId: 'system',
    userName: 'AIXENTRA',
    userAvatar: '',
    content: '🎉 NeonKreyol just hit 2,000 total streams this month!',
    timestamp: new Date(Date.now() - 60 * 1000).toISOString(),
    type: 'system',
  },
];
